scrape_configs:
- job_name: producer
  scrape_interval: 1s
  static_configs:
  - targets:
    - testproducerstatistics:8080
- job_name: consumer
  scrape_interval: 1s
  static_configs:
    - targets:
      - testconsumerstatistics:8080
